export enum EffectGroup {
  Active = 'Active',
  Passive = 'Passive',
}

export enum EffectKindId {
  Revive = 'Revive',
  Heal = 'Heal',
  StartOfStatusBuff = 'StartOfStatusBuff',
  BlockDamage = 'BlockDamage',
  BlockDebuff = 'BlockDebuff',
  ContinuousHeal = 'ContinuousHeal',
  Shield = 'Shield',
  StatusCounterattack = 'StatusCounterattack',
  ReviveOnDeath = 'ReviveOnDeath',
  ShareDamage = 'ShareDamage',
  Unkillable = 'Unkillable',
  DamageCounter = 'DamageCounter',
  ReflectDamage = 'ReflectDamage',
  HitCounterShield = 'HitCounterShield',
  Invisible = 'Invisible',
  ReduceDamageTaken = 'ReduceDamageTaken',
  CrabShell = 'CrabShell',
  CritShield = 'CritShield',
  SkyWrath = 'SkyWrath',
  Enrage = 'Enrage',
  VoidAbyss = 'VoidAbyss',
  StatusIncreaseAttack = 'StatusIncreaseAttack',
  StatusIncreaseDefence = 'StatusIncreaseDefence',
  StatusIncreaseSpeed = 'StatusIncreaseSpeed',
  StatusIncreaseCriticalChance = 'StatusIncreaseCriticalChance',
  StatusChangeDamageMultiplier = 'StatusChangeDamageMultiplier',
  StatusIncreaseAccuracy = 'StatusIncreaseAccuracy',
  StatusIncreaseCriticalDamage = 'StatusIncreaseCriticalDamage',
  EndOfStatusBuff = 'EndOfStatusBuff',
  StartOfStatusDebuff = 'StartOfStatusDebuff',
  Freeze = 'Freeze',
  Provoke = 'Provoke',
  Sleep = 'Sleep',
  Stun = 'Stun',
  BlockHeal = 'BlockHeal',
  BlockActiveSkills = 'BlockActiveSkills',
  ContinuousDamage = 'ContinuousDamage',
  BlockBuffs = 'BlockBuffs',
  TimeBomb = 'TimeBomb',
  IncreaseDamageTaken = 'IncreaseDamageTaken',
  BlockRevive = 'BlockRevive',
  Mark = 'Mark',
  LifeDrainOnDamage = 'LifeDrainOnDamage',
  AoEContinuousDamage = 'AoEContinuousDamage',
  Fear = 'Fear',
  IncreasePoisoning = 'IncreasePoisoning',
  BlockPassiveSkills = 'BlockPassiveSkills',
  StatusReduceAttack = 'StatusReduceAttack',
  StatusReduceDefence = 'StatusReduceDefence',
  StatusReduceSpeed = 'StatusReduceSpeed',
  StatusReduceCriticalChance = 'StatusReduceCriticalChance',
  StatusReduceAccuracy = 'StatusReduceAccuracy',
  StatusReduceCriticalDamage = 'StatusReduceCriticalDamage',
  EndOfStatusDebuff = 'EndOfStatusDebuff',
  ApplyBuff = 'ApplyBuff',
  IncreaseStamina = 'IncreaseStamina',
  RemoveDebuff = 'RemoveDebuff',
  ActivateSkill = 'ActivateSkill',
  ShowHiddenSkill = 'ShowHiddenSkill',
  TeamAttack = 'TeamAttack',
  ExtraTurn = 'ExtraTurn',
  LifeShare = 'LifeShare',
  ReduceCooldown = 'ReduceCooldown',
  ReduceDebuffLifetime = 'ReduceDebuffLifetime',
  IncreaseBuffLifetime = 'IncreaseBuffLifetime',
  PassiveCounterattack = 'PassiveCounterattack',
  PassiveChangeStats = 'PassiveChangeStats',
  PassiveBlockDebuff = 'PassiveBlockDebuff',
  PassiveBonus = 'PassiveBonus',
  MultiplyBuff = 'MultiplyBuff',
  PassiveReflectDamage = 'PassiveReflectDamage',
  PassiveShareDamage = 'PassiveShareDamage',
  IncreaseShield = 'IncreaseShield',
  ReturnDebuffs = 'ReturnDebuffs',
  TransferDebuff = 'TransferDebuff',
  EndOfInstantBuff = 'EndOfInstantBuff',
  ApplyDebuff = 'ApplyDebuff',
  ReduceStamina = 'ReduceStamina',
  StealBuff = 'StealBuff',
  RemoveBuff = 'RemoveBuff',
  IncreaseCooldown = 'IncreaseCooldown',
  ReduceBuffLifetime = 'ReduceBuffLifetime',
  PassiveDebuffLifetime = 'PassiveDebuffLifetime',
  SwapHealth = 'SwapHealth',
  IncreaseDebuffLifetime = 'IncreaseDebuffLifetime',
  DestroyHp = 'DestroyHp',
  Detonate = 'Detonate',
  MultiplyDebuff = 'MultiplyDebuff',
  ReduceShield = 'ReduceShield',
  EndOfInstantDebuff = 'EndOfInstantDebuff',
  Damage = 'Damage',
  HitTypeModifier = 'HitTypeModifier',
  ChangeDefenceModifier = 'ChangeDefenceModifier',
  ChangeEffectAccuracy = 'ChangeEffectAccuracy',
  MultiplyEffectChance = 'MultiplyEffectChance',
  ChangeDamageMultiplier = 'ChangeDamageMultiplier',
  IgnoreProtectionEffects = 'IgnoreProtectionEffects',
  ChangeCalculatedDamage = 'ChangeCalculatedDamage',
  ChangeEffectRepeatCount = 'ChangeEffectRepeatCount',
  ChangeDestroyHpAmount = 'ChangeDestroyHpAmount',
  ChangeHealMultiplier = 'ChangeHealMultiplier',
  ChangeStaminaModifier = 'ChangeStaminaModifier',
  Summon = 'Summon',
  CopyHero = 'CopyHero',
  ChangeEffectTarget = 'ChangeEffectTarget',
  CancelEffect = 'CancelEffect',
  ForceStatusEffectTick = 'ForceStatusEffectTick',
  ChangeSkyWrathCounter = 'ChangeSkyWrathCounter',
  UpdateCombo = 'UpdateCombo',
  SetVoidAbyssCounter = 'SetVoidAbyssCounter',
  StatusBanish = 'StatusBanish',
  Banish = 'Banish',
  EffectDurationModifier = 'EffectDurationModifier',
  CheckTargetForCondition = 'CheckTargetForCondition',
  EffectContainer = 'EffectContainer',
}
export enum EffectTargetType {
  Target = 'Target',
  Producer = 'Producer',
  RelationTarget = 'RelationTarget',
  RelationProducer = 'RelationProducer',
  Owner = 'Owner',
  RandomAlly = 'RandomAlly',
  RandomEnemy = 'RandomEnemy',
  AllAllies = 'AllAllies',
  AllEnemies = 'AllEnemies',
  AllDeadAllies = 'AllDeadAllies',
  RandomDeadAlly = 'RandomDeadAlly',
  RandomDeadEnemy = 'RandomDeadEnemy',
  MostInjuredAlly = 'MostInjuredAlly',
  MostInjuredEnemy = 'MostInjuredEnemy',
  Boss = 'Boss',
  RandomRevivableAlly = 'RandomRevivableAlly',
  OwnerAllies = 'OwnerAllies',
  AllHeroes = 'AllHeroes',
  ActiveHero = 'ActiveHero',
  AllyWithLowestMaxHp = 'AllyWithLowestMaxHp',
  HeroCausedRelationUnapply = 'HeroCausedRelationUnapply',
  HeroThatKilledProducer = 'HeroThatKilledProducer',
  RelationTargetDuplicates = 'RelationTargetDuplicates',
  AllyWithLowestStamina = 'AllyWithLowestStamina',
  AllyWithHighestStamina = 'AllyWithHighestStamina',
  EnemyWithLowestStamina = 'EnemyWithLowestStamina',
  EnemyWithHighestStamina = 'EnemyWithHighestStamina',
  RelationProducerOrTeamAttackInitiator = 'RelationProducerOrTeamAttackInitiator',
}

export enum TargetExclusion {
  Target = 'Target',
  Producer = 'Producer',
  RelationTarget = 'RelationTarget',
  RelationProducer = 'RelationProducer',
}

export enum StatusEffectTypeId {
  Stun = 'Stun',
  Freeze = 'Freeze',
  Sleep = 'Sleep',
  Provoke = 'Provoke',
  Counterattack = 'Counterattack',
  BlockDamage = 'BlockDamage',
  BlockHeal100p = 'BlockHeal100p',
  BlockHeal50p = 'BlockHeal50p',
  ContinuousDamage5p = 'ContinuousDamage5p',
  ContinuousDamage025p = 'ContinuousDamage025p',
  ContinuousHeal075p = 'ContinuousHeal075p',
  ContinuousHeal15p = 'ContinuousHeal15p',
  BlockDebuff = 'BlockDebuff',
  BlockBuffs = 'BlockBuffs',
  IncreaseAttack25 = 'IncreaseAttack25',
  IncreaseAttack50 = 'IncreaseAttack50',
  DecreaseAttack25 = 'DecreaseAttack25',
  DecreaseAttack50 = 'DecreaseAttack50',
  IncreaseDefence30 = 'IncreaseDefence30',
  IncreaseDefence60 = 'IncreaseDefence60',
  DecreaseDefence30 = 'DecreaseDefence30',
  DecreaseDefence60 = 'DecreaseDefence60',
  IncreaseSpeed15 = 'IncreaseSpeed15',
  IncreaseSpeed30 = 'IncreaseSpeed30',
  DecreaseSpeed15 = 'DecreaseSpeed15',
  DecreaseSpeed30 = 'DecreaseSpeed30',
  IncreaseAccuracy25 = 'IncreaseAccuracy25',
  IncreaseAccuracy50 = 'IncreaseAccuracy50',
  DecreaseAccuracy25 = 'DecreaseAccuracy25',
  DecreaseAccuracy50 = 'DecreaseAccuracy50',
  IncreaseCriticalChance15 = 'IncreaseCriticalChance15',
  IncreaseCriticalChance30 = 'IncreaseCriticalChance30',
  DecreaseCriticalChance15 = 'DecreaseCriticalChance15',
  DecreaseCriticalChance30 = 'DecreaseCriticalChance30',
  IncreaseCriticalDamage15 = 'IncreaseCriticalDamage15',
  IncreaseCriticalDamage30 = 'IncreaseCriticalDamage30',
  DecreaseCriticalDamage15p = 'DecreaseCriticalDamage15p',
  DecreaseCriticalDamage25p = 'DecreaseCriticalDamage25p',
  Shield = 'Shield',
  BlockActiveSkills = 'BlockActiveSkills',
  ReviveOnDeath = 'ReviveOnDeath',
  ShareDamage50 = 'ShareDamage50',
  ShareDamage25 = 'ShareDamage25',
  Unkillable = 'Unkillable',
  TimeBomb = 'TimeBomb',
  DamageCounter = 'DamageCounter',
  IncreaseDamageTaken25 = 'IncreaseDamageTaken25',
  IncreaseDamageTaken15 = 'IncreaseDamageTaken15',
  BlockRevive = 'BlockRevive',
  ArtifactSet_Shield = 'ArtifactSet_Shield',
  ReflectDamage15 = 'ReflectDamage15',
  ReflectDamage30 = 'ReflectDamage30',
  MinotaurIncreaseDamage = 'MinotaurIncreaseDamage',
  MinotaurIncreaseDamageTaken = 'MinotaurIncreaseDamageTaken',
  Mark = 'Mark',
  HitCounterShield = 'HitCounterShield',
  LifeDrainOnDamage10p = 'LifeDrainOnDamage10p',
  Burn = 'Burn',
  Invisible1 = 'Invisible1',
  Invisible2 = 'Invisible2',
  Fear1 = 'Fear1',
  Fear2 = 'Fear2',
  IncreasePoisoning25 = 'IncreasePoisoning25',
  IncreasePoisoning50 = 'IncreasePoisoning50',
  ReduceDamageTaken15 = 'ReduceDamageTaken15',
  ReduceDamageTaken25 = 'ReduceDamageTaken25',
  CrabShell = 'CrabShell',
  CritShield25 = 'CritShield25',
  CritShield50 = 'CritShield50',
  CritShield75 = 'CritShield75',
  CritShield100 = 'CritShield100',
  SkyWrath = 'SkyWrath',
  Enrage = 'Enrage',
  BlockPassiveSkills = 'BlockPassiveSkills',
  StatusBanish = 'StatusBanish',
  VoidAbyss = 'VoidAbyss',
}

export enum EffectKindGroup {
  Undefined = 'Undefined',
  StatusDebuff = 'StatusDebuff',
  ResistibleInstantDebuff = 'ResistibleInstantDebuff',
  EffectThatApplyStatusDebuffs = 'EffectThatApplyStatusDebuffs',
}

export enum LifetimeUpdateType {
  OnStartTurn = 'OnStartTurn',
  OnEndTurn = 'OnEndTurn',
  Custom = 'Custom',
}

export enum ApplyMode {
  Unresistable = 'Unresistable',
  Guaranteed = 'Guaranteed',
}

export enum ProtectionMode {
  ProtectedFromEnemies = 'ProtectedFromEnemies',
  FullyProtected = 'FullyProtected',
}

export enum UnapplyEffectTarget {
  Target = 'Target',
  Producer = 'Producer',
}

export enum UnapplyEffectMode {
  Selected = 'Selected',
  AllExceptSelected = 'AllExceptSelected',
}

export enum HitType {
  Normal = 'Normal',
  Crushing = 'Crushing',
  Critical = 'Critical',
  Glancing = 'Glancing',
}

export enum ElementRelation {
  Disadvantage = 'Disadvantage',
  Neutral = 'Neutral',
  Advantage = 'Advantage',
}

export enum EvenMode {
  Average = 'Average',
  Highest = 'Highest',
  Lowest = 'Lowest',
}

export enum ActivateSkillOwner {
  Producer = 'Producer',
  Target = 'Target',
}

export enum SkillToChange {
  Random = 'Random',
  ByIndex = 'ByIndex',
  SkillOfCurrentContext = 'SkillOfCurrentContext',
  All = 'All',
}

export enum AppliedEffectType {
  Buff = 'Buff',
  Debuff = 'Debuff',
}

export enum CrabShellLayerType {
  First = 'First',
  Second = 'Second',
  Third = 'Third',
}

export enum PassiveBonus {
  Heal = 'Heal',
  ShieldCreation = 'ShieldCreation',
  StaminaRecovery = 'StaminaRecovery',
  ArtifactSetStats = 'ArtifactSetStats',
}

export enum SkillBonusType {
  Attack = 'Attack',
  Health = 'Health',
  EffectChance = 'EffectChance',
  CooltimeTurn = 'CooltimeTurn',
  ShieldCreation = 'ShieldCreation',
}
