using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Raid.Toolkit;

public static class Constants
{
	public static readonly string TargetProcessName = "Raid";
	public static readonly string IPCPipeName = "rtk_367f1fbd-0b13-4b14-9bb3-f04a3bdc977e";
	public static readonly string ExtensionManifestFileName = ".rtk.extension.json";

	public static readonly string[] SDKAssemblies = new string[]{
		"ColorCode.Core",
		"ColorCode.WinUI",
		"CommandLine",
		"CommunityToolkit.Common",
		"CommunityToolkit.WinUI",
		"CommunityToolkit.WinUI.Notifications",
		"CommunityToolkit.WinUI.UI.Controls.Core",
		"CommunityToolkit.WinUI.UI.Controls.DataGrid",
		"CommunityToolkit.WinUI.UI.Controls.Input",
		"CommunityToolkit.WinUI.UI.Controls.Layout",
		"CommunityToolkit.WinUI.UI.Controls.Markdown",
		"CommunityToolkit.WinUI.UI.Controls.Media",
		"CommunityToolkit.WinUI.UI.Controls.Primitives",
		"CommunityToolkit.WinUI.UI",
		"CustomExtensions.WinUI",
		"Google.Protobuf",
		"Grpc.Core.Api",
		"Grpc.Net.Client",
		"Grpc.Net.Common",
		"Il2CppToolkit.Common",
		"Il2CppToolkit.Injection.Client",
		"Il2CppToolkit.Injection.Host",
		"Il2CppToolkit.Metadata",
		"Il2CppToolkit.ReverseCompiler",
		"Il2CppToolkit.Runtime",
		"Il2CppToolkit.Target.NetCore",
		"Karambolo.Extensions.Logging.File",
		"Microsoft.Extensions.Configuration.Abstractions",
		"Microsoft.Extensions.Configuration.Binder",
		"Microsoft.Extensions.Configuration.CommandLine",
		"Microsoft.Extensions.Configuration",
		"Microsoft.Extensions.Configuration.EnvironmentVariables",
		"Microsoft.Extensions.Configuration.FileExtensions",
		"Microsoft.Extensions.Configuration.Json",
		"Microsoft.Extensions.Configuration.UserSecrets",
		"Microsoft.Extensions.DependencyInjection.Abstractions",
		"Microsoft.Extensions.DependencyInjection",
		"Microsoft.Extensions.FileProviders.Abstractions",
		"Microsoft.Extensions.FileProviders.Physical",
		"Microsoft.Extensions.FileSystemGlobbing",
		"Microsoft.Extensions.Hosting.Abstractions",
		"Microsoft.Extensions.Hosting",
		"Microsoft.Extensions.Logging.Abstractions",
		"Microsoft.Extensions.Logging.Configuration",
		"Microsoft.Extensions.Logging.Console",
		"Microsoft.Extensions.Logging.Debug",
		"Microsoft.Extensions.Logging",
		"Microsoft.Extensions.Logging.EventLog",
		"Microsoft.Extensions.Logging.EventSource",
		"Microsoft.Extensions.Options.ConfigurationExtensions",
		"Microsoft.Extensions.Options",
		"Microsoft.Extensions.Primitives",
		"Microsoft.Graphics.Canvas",
		"Microsoft.Graphics.Canvas.Interop",
		"Microsoft.InteractiveExperiences.Projection",
		"Microsoft.Windows.ApplicationModel.DynamicDependency.Projection",
		"Microsoft.Windows.ApplicationModel.Resources.Projection",
		"Microsoft.Windows.ApplicationModel.WindowsAppRuntime.Projection",
		"Microsoft.Windows.AppLifecycle.Projection",
		"Microsoft.Windows.AppNotifications.Builder.Projection",
		"Microsoft.Windows.AppNotifications.Projection",
		"Microsoft.Windows.PushNotifications.Projection",
		"Microsoft.Windows.SDK.NET",
		"Microsoft.Windows.Security.AccessControl.Projection",
		"Microsoft.Windows.System.Power.Projection",
		"Microsoft.Windows.System.Projection",
		"Microsoft.Windows.Widgets.Providers.Projection",
		"Microsoft.WindowsAppRuntime.Bootstrap",
		"Microsoft.WindowsAppRuntime.Bootstrap.Net",
		"Microsoft.WinUI",
		"Mono.Cecil",
		"Mono.Cecil.Mdb",
		"Mono.Cecil.Pdb",
		"Mono.Cecil.Rocks",
		"Newtonsoft.Json",
		"ProcessMemoryUtilities",
		"Raid.Toolkit.Common",
		"Raid.Toolkit",
		"Raid.Toolkit.Extensibility",
		"Raid.Toolkit.Extensibility.Host",
		"Raid.Toolkit.ExtensionHost",
		"Raid.Toolkit.Loader",
		"System.Diagnostics.EventLog.Messages",
		"System.Threading.Tasks.Dataflow",
		"Vestris.ResourceLib",
		"WinRT.Runtime",
		"WinUIEx",
	};
}
