name: Buddy Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    env:
      IS_CI: true
      Solution_Name: SDK.sln
      App_csproj: src\Application\Raid.Toolkit\Raid.Toolkit.csproj
      Client_csproj: src\ClientSDK\DotNet\Raid.Client.csproj

    steps:
      - uses: mickem/clean-after-action@v1

      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set branch-based environment variables
        uses: iamtheyammer/branch-env-vars@v1.0.4
        with:
          PRERELEASE: |
            main:true
            !default:false

      # Install the .NET Core workload
      - name: Install .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: |
            5.0.x
            6.0.x

      # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.0.2

      # Versions
      - uses: dotnet/nbgv@master
        id: rtk_version
        with:
          setAllVars: true

      # Restore the application to populate the obj folder with RuntimeIdentifiers
      - name: Restore the application
        run: msbuild $env:Solution_Name /t:Restore /p:Configuration=Release

      # Publish RTK
      - name: Publish App
        run: |
          msbuild $env:Solution_Name -m -t:"Build;Pack" -p:Configuration=Release -p:Platform=x64 -p:PackageOutputPath="$(Get-Location)\publish\nuget"

      - name: Build Setup
        run: |
          candle.exe -nologo -o out\ RaidToolkitBinaries.wxs Product.wxs Bundle.wxs -ext WixBalExtension
          light.exe -nologo -o out\RaidToolkit.msi out\Product.wixobj out\RaidToolkitBinaries.wixobj -ext WixBalExtension
          light.exe -nologo -o out\RaidToolkit.exe out\Bundle.wixobj -ext WixBalExtension
        working-directory: ./src/Setup
        env:
          AppVersion: ${{ steps.rtk_version.outputs.Version }}
          Prerelease: 1
          BuildOutputDirectory: ..\Application\Raid.Toolkit\bin\x64\Release\net6.0-windows10.0.19041.0\win10-x64
